### ISSUE TITLE
AttributeError: module 'MinkowskiEngineBackend' has no attribute 'ConvolutionForwardGPUf'

### ISSUE THREAD

**Issue by samfux84** [StanfordVL/MinkowskiEngine#113]
Hi,

A user on our HPC cluster was running a job with MinkowskiEngine 0.4.2 (Pytorch 1.4.0, Torchvision 0.5.0, six 1.12.0, numpy 1.18.2, Pillow 6.2.0) and received the following error:

```
03/27 00:24:38 Resetting the data loader seed to 0
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    main(config)
  File "train.py", line 63, in main
    trainer.train()
  File "/cluster/scratch/majing/FCGF/lib/trainer.py", line 125, in train
    val_dict = self._valid_epoch()
  File "/cluster/scratch/majing/FCGF/lib/trainer.py", line 320, in _valid_epoch
    F0 = self.model(sinput0).F
  File "/cluster/home/majing/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/scratch/majing/FCGF/model/resunet.py", line 143, in forward
    out_s1 = self.conv1(x)
  File "/cluster/home/majing/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/cluster/home/majing/.local/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 278, in forward
    out_coords_key, input.coords_man)
  File "/cluster/home/majing/.local/lib/python3.7/site-packages/MinkowskiEngine-0.4.2-py3.7-linux-x86_64.egg/MinkowskiEngine/MinkowskiConvolution.py", line 86, in forward
    fw_fn = getattr(MEB, 'ConvolutionForward' + get_postfix(input_features))
AttributeError: module 'MinkowskiEngineBackend' has no attribute 'ConvolutionForwardGPUf'
```

Is this a known problem ?

Any help is appreciated.

Best regards

Sam

**Comment by chrischoy** [comment]
It is installed with --cpu_only during installation and it seems it is able to access GPU during runtime.

This happens when you compile in a cluster with CPU only and run it on other nodes with GPU.

**Comment by chrischoy** [comment]
Another thread with the same problem. https://github.com/chrischoy/FCGF/issues/24

**Comment by samfux84** [comment]
@chrischoy : Thank you for the reply.

Reinstallation of the package on a node with a GPU solved the problem.

Thank you for your support.
