### ISSUE TITLE
ValueError: too many values to unpack

### ISSUE THREAD

**Issue by ElectronicElephant** [StanfordVL/MinkowskiEngine#128]
When running `python -m examples.reconstruction`, I got these errors.

```
server 04/22 10:09:39 Loading weights from modelnet_reconstruction.pth
Traceback (most recent call last):
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/disk1/home/server/MinkowskiEngine/examples/reconstruction.py", line 625, in <module>
    visualize(net, dataloader, device, config)
  File "/disk1/home/server/MinkowskiEngine/examples/reconstruction.py", line 546, in visualize
    for data_dict in dataloader:
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44,
in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk1/home/server/.conda/envs/py3-mink/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44,
in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/disk1/home/server/MinkowskiEngine/examples/reconstruction.py", line 151, in __getitem__
    inds = ME.utils.sparse_quantize(coords, return_index=True)
  File "/disk1/home/server/MinkowskiEngine/MinkowskiEngine/utils/quantization.py", line 243, in sparse_quantize
    unique_map, inverse_map = quantize(discrete_coords)
ValueError: too many values to unpack (expected 2)
```

It seems that what `quantize` returned was a list too large.

I'm running Ubuntu 16.04, CUDA 10.1, gcc 7.5. Have no idea how to fix.  It will be appreciated if you can give some hint. Thanks.

**Comment by ElectronicElephant** [comment]
I reset to 0.4.2 (`d212be80`) and now it's working.
