### ISSUE TITLE
TypeError: 'SparseTensor' object does not support indexing

### ISSUE THREAD

**Issue by shiba24** [StanfordVL/MinkowskiEngine#136]
Hello, I am getting a strange bug.

I am now trying to train ResNet34 (from https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/resnet.py ) on PointCloud-like data.

input sparse tensor is

```
SparseTensor(
  Coords=tensor([[  0, 273, 247,  -1],
        [  0, 629, 248,   0],
        [  0, 733, 249,   1],
        ...,
        [  3,  74, 253,   3],
        [  3, 734, 261,  -3],
        [  3, 326, 255,  -3]], dtype=torch.int32)
  Feats=tensor([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [0.],
        [1.]])
  coords_key=< CoordsKey, key: 15034981587763204738, tensor_stride: [1, 1, 1] in dimension: 3 >
  tensor_stride=[1, 1, 1]
  coords_man=< CoordsManager
	Number of Coordinate Maps: 1 
		Coordinate Map Key: 15034981587763204738, Size: 39997
	Number of Kernel Maps: 0 >
)
```

And the model definition is using https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/resnet.py

```
ResNet34(1, 6)
```

Then, the bug is when I run forward calculation.

```
Traceback (most recent call last):

  File "train_pointnet.py", line 400, in <module>
    pointnet_trainer.train()
  File "train_pointnet.py", line 194, in train
    self.run_epoch()
  File "train_pointnet.py", line 213, in run_epoch
    outputs, losses = self.process_batch(inputs)
  File "train_pointnet.py", line 244, in process_batch
    out_sparse_tensor = self.models["encoder"](inputs["ST", 0, -1])
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__                     
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/point-learner/networks/sparseconvnet.py", line 101, in forward                                                       
    x = self.conv1(x)
  File "/home/ubuntu/.pyenv/versions/3.6.8/lib/python3.6/site-packages/torch/nn/modules/module.py", line 543, in __call__                     
    var = var[0]
TypeError: 'SparseTensor' object does not support indexing
```

More interesting thing is, when I run this code on Jupyter Notebook, it **works without any error**.
When I run it from terminal, it raises this error.

Does anyone have a similar issue or have any idea to solve it?

Thank you very much!

**Comment by shiba24** [comment]
Oh, after a bit of experiments I found the root cause - it was not this library.
There is a library called `wandb`, and when you use `wandb.watch` for MinkowskiConvolution etc., it raises the error.

https://docs.wandb.com/library/frameworks/pytorch
