### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SwagJ** [StanfordVL/MinkowskiEngine#165]
Hi, 

When I run with command: 
export CUDA_HOME=/usr/local/cuda; python setup.py install 
from source. I came across this error here. Do you know how to solve this?

Using BLAS=openblas
CXX src/region.cpp
CXX src/coordsmap.cpp
CXX src/pooling_global_max.cpp
CXX src/pooling_transpose.cpp
CXX src/convolution_transpose.cpp
CXX src/coords_manager.cpp
CXX src/union.cpp
CXX src/broadcast.cpp
CXX src/pruning.cpp
CXX src/pooling_global_avg.cpp
CXX src/math_functions.cpp
CXX src/pooling_avg.cpp
CXX src/quantization.cpp
CXX src/coords_key.cpp
CXX src/pooling_max.cpp
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_avg.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_transpose.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/coords_manager.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_global_avg.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/coords_key.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/convolution_transpose.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pruning.hpp:28,
                 from src/pruning.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/union.hpp:28,
                 from src/union.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_global_max.cpp:21:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/broadcast.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
In file included from src/coords_manager.hpp:46:0,
                 from src/common.hpp:34,
                 from src/pooling_max.cpp:25:
src/gpu_memory_manager.hpp: In member function ‘void* minkowski::GPUMemoryManager::gpuMalloc(size_t)’:
src/gpu_memory_manager.hpp:111:51: error: ‘raw_alloc_with_stream’ is not a member of ‘c10::cuda::CUDACachingAllocator’
       p_buffer = c10::cuda::CUDACachingAllocator::raw_alloc_with_stream(
                                                   ^~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:163: objs/coords_key.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:163: objs/pooling_avg.o] Error 1
make: *** [Makefile:163: objs/pooling_transpose.o] Error 1
make: *** [Makefile:163: objs/pooling_global_max.o] Error 1
make: *** [Makefile:163: objs/pruning.o] Error 1
make: *** [Makefile:163: objs/union.o] Error 1
make: *** [Makefile:163: objs/pooling_global_avg.o] Error 1
make: *** [Makefile:163: objs/convolution_transpose.o] Error 1
make: *** [Makefile:163: objs/broadcast.o] Error 1
make: *** [Makefile:163: objs/coords_manager.o] Error 1
make: *** [Makefile:163: objs/pooling_max.o] Error 1
Traceback (most recent call last):
  File "setup.py", line 188, in <module>
    run_command(*compile_args)
  File "setup.py", line 90, in run_command
    subprocess.check_call(args)
  File "/home/hashswan/.conda/envs/fcgf/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j12', 'PYTHON=/home/hashswan/.conda/envs/fcgf/bin/python', 'BLAS=openblas')' returned non-zero exit status 2.

Thank you very much.

**Comment by SwagJ** [comment]
Fix by setting correct version of pytorch
