### ISSUE TITLE
Type mismatch in feats during Convolution

### ISSUE THREAD

**Issue by aniqueakhtar** [StanfordVL/MinkowskiEngine#170]
Not sure if this is an error or not but I was getting a type mismatch error even when `inputs.F` was float.

```
>>> inputs                   
SparseTensor(                
  Coords=tensor([[  0,   9,  58,  30],
        [  0,   9,  58,  32],
        [  0,   9,  60,  30],
        ...,                                     
        [ 31,  88, 105,   3],            
        [ 31,  88, 105,   5],    
        [ 31,  88, 107,   1]], dtype=torch.int32)
  Feats=tensor([[0.0703, 0.4531, 0.2344],
        [0.0703, 0.4531, 0.2500],
        [0.0703, 0.4688, 0.2344],
        ...,
        [0.6875, 0.8203, 0.0234],
        [0.6875, 0.8203, 0.0391],
        [0.6875, 0.8359, 0.0078]], device='cuda:0', dtype=torch.float64)
  coords_key=< CoordsKey, key: 15034981587763204738, tensor_stride: [1, 1, 1] in dimension: 3 >
  tensor_stride=[1, 1, 1]
  coords_man=< CoordsManager
        Number of Coordinate Maps: 1
                Coordinate Map Key: 15034981587763204738, Size: 292433
        Number of Kernel Maps: 0 >
  spatial dimension=3)

>>> inputs.F
tensor([[0.0703, 0.4531, 0.2344],
        [0.0703, 0.4531, 0.2500],
        [0.0703, 0.4688, 0.2344],
        ...,
        [0.6875, 0.8203, 0.0234],
        [0.6875, 0.8203, 0.0391],
        [0.6875, 0.8359, 0.0078]], device='cuda:0', dtype=torch.float64)

>>> output = model(inputs)                                                
Traceback (most recent call last):                                     
  File "<stdin>", line 1, in <module>                                                          
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anique/Upsampling_1/Mink1/v1/minkunet.py", line 118, in forward
    out = self.conv0p1s1(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiConvolution.py", line 281, in forward
    input.coords_man)
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiConvolution.py", line 65, in forward
    f"Type mismatch input: {input_features.type()} != kernel: {kernel.type()}"
AssertionError: Type mismatch input: torch.cuda.DoubleTensor != kernel: torch.cuda.FloatTensor
```

However, there was no error when

```
>>> inputs                                                                                                                                                                               
SparseTensor(                                                                                                                                                                            
  Coords=tensor([[  0,   0,  51,  94],                                                                                                                                                   
        [  0,   0,  51,  96],                                                                                                                                                            
        [  0,   0,  51,  98],                                                                                                                                                            
        ...,                                                                                                                                                                             
        [ 31, 110,   1,  98],                                                                                                                                                            
        [ 31, 110,   1, 100],                                                                                                                                                            
        [ 31, 110,   1, 102]], dtype=torch.int32)                                                                                                                                        
  Feats=tensor([[0.0000, 0.3984, 0.7344],                                                                                                                                                
        [0.0000, 0.3984, 0.7500],                                                                                                                                                        
        [0.0000, 0.3984, 0.7656],                                                                                                                                                        
        ...,                                                                                                                                                                             
        [0.8594, 0.0078, 0.7656],                                                                                                                                                        
        [0.8594, 0.0078, 0.7812],                                                                                                                                                        
        [0.8594, 0.0078, 0.7969]], device='cuda:0')                                                                                                                                      
  coords_key=< CoordsKey, key: 15034981587763204738, tensor_stride: [1, 1, 1] in dimension: 3 >                                                                                          
  tensor_stride=[1, 1, 1]                                                                                                                                                                
  coords_man=< CoordsManager                                           
        Number of Coordinate Maps: 1                                                                         
                Coordinate Map Key: 15034981587763204738, Size: 268113
        Number of Kernel Maps: 0 >                                                                                        
  spatial dimension=3)                                                        
>>> output = model(inputs)   
```

I don't know if this is how it is supposed to be but just wanted to let people know.

**Comment by chrischoy** [comment]
This is not an error

```
model = model.double()
output = model(input.double())  # works

model = model.float()
output = model(input.float()) # works

model.float()
output = model(input.double()) # Error
```
