### ISSUE TITLE
GPU problem

### ISSUE THREAD

**Issue by GaoQiyu** [StanfordVL/MinkowskiEngine#45]
when I use only one gpu but not the cuda:0 device
it always print this :

Traceback (most recent call last):
  File "train.py", line 208, in <module>
    trainer.train(epoch)
  File "train.py", line 81, in train
    output_sparse = self.model(point)
  File "/home/gaoqiyu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaoqiyu/PointCloudSeg_Minkowski/model/res16unet.py", line 197, in forward
    out = self.conv0p1s1(x)
  File "/home/gaoqiyu/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/gaoqiyu/PointCloudSeg_Minkowski/MinkowskiEngine/MinkowskiConvolution.py", line 270, in forward
    out_coords_key, input.coords_man)
  File "/home/gaoqiyu/PointCloudSeg_Minkowski/MinkowskiEngine/MinkowskiConvolution.py", line 91, in forward
    ctx.coords_man.CPPCoordsManager)
RuntimeError:  an illegal memory access was encountered at src/convolution.cu:259

I wonder if this is the problem of my system?

**Comment by chrischoy** [comment]
Seems related to this https://github.com/StanfordVL/MinkowskiEngine/issues/40

**Comment by chrischoy** [comment]
This should not happen for sure. I'll dig deeper into this after some deadlines.

**Comment by murrdpirate** [comment]
I seem to be having this issue as well. Using the default cuda device works without issues.

I'm running:
* MinkowskiEngine 0.4.3
* cuda 10.2
* python 3.7.7
* pytorch 1.5.0

I'm actually running FCGF, but I figured this was the best place to mention the issue.

Here's the output (basically same as @GaoQiyu ):

Traceback (most recent call last):
  File "test.py", line 80, in <module>
    main(config)
  File "test.py", line 55, in main
    trainer._valid_epoch()
  File "/home/km/workspaces/FCGF/lib/trainer.py", line 338, in _valid_epoch
    F0 = self.model(sinput0).F
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/km/workspaces/FCGF/model/resunet.py", line 143, in forward
    out_s1 = self.conv1(x)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiConvolution.py", line 281, in forward
    input.coords_man)
  File "/usr/local/lib/python3.7/dist-packages/MinkowskiEngine/MinkowskiConvolution.py", line 92, in forward
    ctx.coords_man.CPPCoordsManager)
RuntimeError:  an illegal memory access was encountered at src/convolution.cu:285

**Comment by chrischoy** [comment]
Seems like the default cuda calls for cuda malloc and the pytorch default GPU are using different GPU IDs.
