### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by NguyenVanThanhHust** [StanfordVL/MinkowskiEngine#52]
Hi, I try this with aws server because my personal computer doesn't have enough memory. 

I use this inside docker. I compiled successfully.

g++ version: 
`g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0`

Cuda version: 
`release 10.1, V10.1.243`

error: 
`Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/share/Projects/ThanhNV/MinkowskiEngine/examples/example.py", line 80, in <module>
    output = net(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/share/Projects/ThanhNV/MinkowskiEngine/examples/example.py", line 56, in forward
    return self.net(x)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/workspace/share/Projects/ThanhNV/MinkowskiEngine/MinkowskiEngine/MinkowskiNormalization.py", line 58, in forward
    output = self.bn(input.F)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 539, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 72, in forward
    self.num_batches_tracked += 1
RuntimeError: CUDA error: no kernel image is available for execution on the device
`
pytorch version:
`'1.2.0a0+e6a7071`

When i install this library on docker, i also use this command: `apt install libgl1-mesa-glx` because default open3d cannot be imported. 

Does anyone have any ideas about this problem? 
Thank you.

**Comment by chrischoy** [comment]
This is the same error in pytorch https://github.com/pytorch/pytorch/issues/6529 which states that the GPU that you are using is no longer supported by pytorch.

**Comment by NguyenVanThanhHust** [comment]
Thanks.

**Comment by Pxiaoyao** [comment]
Has the problem been solved?
