### ISSUE TITLE
RuntimeError:  invalid device function at src/convolution.cu:281

### ISSUE THREAD

**Issue by phongnhhn92** [StanfordVL/MinkowskiEngine#63]
Hello, 
I have followed the guide and install the Engine.
When I try to run the example script 
`python -m examples.example`

I received this error:

```
(py3-mink) phong@phong-Server:~/data/Work/Experiments/MinkowskiEngine$ python -m examples.example
ExampleNetwork(
  (net): Sequential(
    (0): MinkowskiConvolution(in=3, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])
    (1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): MinkowskiReLU()
    (3): MinkowskiConvolution(in=64, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])
    (4): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): MinkowskiReLU()
    (6): MinkowskiGlobalPooling(average=True)
    (7): MinkowskiLinear(in_features=128, out_features=5, bias=True)
  )
)
Traceback (most recent call last):
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/phong/data/Work/Experiments/MinkowskiEngine/examples/example.py", line 80, in <module>
    output = net(input)
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/phong/data/Work/Experiments/MinkowskiEngine/examples/example.py", line 56, in forward
    return self.net(x)
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/phong/miniconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/phong/data/Work/Experiments/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 272, in forward
    out_coords_key, input.coords_man)
  File "/home/phong/data/Work/Experiments/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 92, in forward
    ctx.coords_man.CPPCoordsManager)
RuntimeError:  invalid device function at src/convolution.cu:281
Segmentation fault (core dumped)
```
Please help!

**Comment by chrischoy** [comment]
I suspect the error was due to the compiled binary not supporting the device. What GPU are u using?

**Comment by chrischoy** [comment]
The error seems to be fixed on the latest versions of the MinkowskiEngine with the cudaMalloc instead of torch memory allocation https://github.com/StanfordVL/MinkowskiEngine/commit/8195f630983d950020a5d31f71f1846935708e9b.

**Comment by peiyunh** [comment]
I also run into this issue when I do `python -m examples.example`. I installed through conda. 

```
(py3-mink) peiyunh@voxel:~/work/MinkowskiEngine (master=) $ python -m examples.example                                             
ExampleNetwork(                                                                                                                    
  (net): Sequential(                                                                                                               
    (0): MinkowskiConvolution(in=3, out=64, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])  
    (1): MinkowskiBatchNorm(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)                                    
    (2): MinkowskiReLU()                                                                                                           
    (3): MinkowskiConvolution(in=64, out=128, region_type=RegionType.HYPERCUBE, kernel_size=[3, 3], stride=[2, 2], dilation=[1, 1])
    (4): MinkowskiBatchNorm(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)                                   
    (5): MinkowskiReLU()                                                                                                           
    (6): MinkowskiGlobalPooling(average=True)                                                                                      
    (7): MinkowskiLinear(in_features=128, out_features=5, bias=True)                                                               
  )                                                                                                                                
)                                                                                                                                  
Traceback (most recent call last):                                                                                                 
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 193, in _run_module_as_main                            
    "__main__", mod_spec)                                                                                                          
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/runpy.py", line 85, in _run_code                                       
    exec(code, run_globals)                                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/examples/example.py", line 80, in <module>                                              
    output = net(input)                                                                                                            
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/examples/example.py", line 56, in forward                                               
    return self.net(x)                                                                                                             
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/container.py", line 92, in forward      
    input = module(input)                                                                                                          
  File "/home/peiyunh/anaconda3/envs/py3-mink/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__       
    result = self.forward(*input, **kwargs)                                                                                        
  File "/home/peiyunh/work/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 278, in forward                          
    out_coords_key, input.coords_man)                                                                                              
  File "/home/peiyunh/work/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 93, in forward                           
    ctx.coords_man.CPPCoordsManager)                                                                                               
RuntimeError:  invalid device function at src/convolution.cu:283                                                                   
Segmentation fault (core dumped)                                                                                                   
```
