### ISSUE TITLE
Multi-gpu example AssertionError in parallel.parallel_apply

### ISSUE THREAD

**Issue by filipeaggaspar** [StanfordVL/MinkowskiEngine#82]
Hi, I'm trying to run the [multigpu](https://github.com/StanfordVL/MinkowskiEngine/blob/master/examples/multigpu.py) example in version 0.4.1 but I always run into this error:

`
python -m examples.multigpu --max_ngpu=1

Testing  1  GPUs. Total batch size:  4
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/filipe/dev/MinkowskiEngine/examples/multigpu.py", line 114, in <module>
    outputs = parallel.parallel_apply(replicas, inputs, devices=devices)
  File "/home/filipe/dev/MinkowskiEngine/env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/home/filipe/dev/MinkowskiEngine/env/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
AssertionError: Caught AssertionError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/filipe/dev/MinkowskiEngine/env/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/filipe/dev/MinkowskiEngine/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/filipe/dev/MinkowskiEngine/examples/minkunet.py", line 123, in forward
    out = self.conv0p1s1(x)
  File "/home/filipe/dev/MinkowskiEngine/env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/filipe/dev/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 278, in forward
    out_coords_key, input.coords_man)
  File "/home/filipe/dev/MinkowskiEngine/MinkowskiEngine/MinkowskiConvolution.py", line 66, in forward
    f"Type mismatch input: {input_features.type()} != kernel: {kernel.type()}"
AssertionError: Type mismatch input: torch.cuda.DoubleTensor != kernel: torch.cuda.FloatTensor

`

Any idea why this is failing? I'm using python 3.7 in and virtualenv. I installed MinkowskiEngine using pip3 (as described in the readme). I'm running the code using Ubuntu 18.04, CUDA 10.1, with 1 and 2 GeForce GTX 1080.

Thanks for making your research available in github.
Cheers,
Filipe

**Comment by chrischoy** [comment]
The error says

`AssertionError: Type mismatch input: torch.cuda.DoubleTensor != kernel: torch.cuda.FloatTensor`

It literally means that types don’t match. Input: double, kernel: float. Match the input type by `.float()`

**Comment by filipeaggaspar** [comment]
Got it, solved. Thanks
